/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/day-detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/upgrade`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shopping` | `/shopping`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stores` | `/stores`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/budget`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/restrictions`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/splash`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/day-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/upgrade`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/shopping` | `/shopping`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stores` | `/stores`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/budget`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/goal`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/restrictions`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/splash`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/day-detail${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/upgrade${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/shopping${`?${string}` | `#${string}` | ''}` | `/shopping${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stores${`?${string}` | `#${string}` | ''}` | `/stores${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/onboarding/budget${`?${string}` | `#${string}` | ''}` | `/onboarding/goal${`?${string}` | `#${string}` | ''}` | `/onboarding/restrictions${`?${string}` | `#${string}` | ''}` | `/onboarding/splash${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/day-detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/upgrade`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shopping` | `/shopping`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stores` | `/stores`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/budget`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/restrictions`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/splash`; params?: Router.UnknownInputParams; };
    }
  }
}
